# Generated by Django 4.2 on 2023-05-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maincategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=50)),
                ('final_price', models.CharField(max_length=20)),
                ('base_price', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=30)),
                ('discription', models.TextField()),
                ('pic1', models.ImageField(upload_to='product')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='product')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='product')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='product')),
                ('pic5', models.ImageField(blank=True, default=None, null=True, upload_to='product')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionApp.brand')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionApp.maincategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionApp.subcategory')),
            ],
        ),
    ]
