# Generated by Django 4.2 on 2023-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
