# Generated by Django 4.2 on 2023-05-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0002_product_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
