# Generated by Django 4.2 on 2023-06-02 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0005_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
    ]
