# Generated by Django 4.2 on 2023-06-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0009_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
