# Generated by Django 4.2 on 2023-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0010_buyers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='addressline1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='addressline2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='addressline3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='buyers'),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='pin',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='buyers',
            name='state',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
