# Generated by Django 4.2 on 2023-06-30 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0011_alter_buyers_addressline1_alter_buyers_addressline2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionApp.buyers')),
            ],
        ),
    ]
