# Generated by Django 4.2 on 2023-07-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0014_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutproducts',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
