# Generated by Django 4.2 on 2023-07-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='otp',
            field=models.IntegerField(default=-12333111),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='orderStatus',
            field=models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Order is Dispatch'), (3, ' Dispatched'), (4, 'Out for Delivery'), (5, 'Delivered')], default=1),
        ),
    ]
