# Generated by Django 4.2 on 2023-07-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashionApp', '0017_buyers_otp_alter_checkout_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='rppid',
            field=models.CharField(default='', max_length=30),
        ),
    ]
